### ISSUE TITLE
IE (de)serialization of anonymous object

### ISSUE THREAD

**Issue by GrumpyMeow** [erossignon/serialijse#3]
(de)serialization of anonymous objects will not work.
In IE the object.constructor.name will fall all the way through the extract_object_classname function. This function should always return an objectname, even if it is "object".

 function extract_object_classname(object) {
        var className =  object.constructor.name;
        if (className) {
            return className;
        }
        if(object instanceof Float32Array) { return "Float32Array"; }
        if(object instanceof Uint32Array) { return "Uint32Array"; }
        if(object instanceof Uint16Array) { return "Uint16Array"; }
        if(object instanceof Uint8Array) { return "Uint8Array"; }
        if(object instanceof Int32Array) { return "Int32Array"; }
        if(object instanceof Int16Array) { return "Int16Array"; }
        if(object instanceof Int8Array) { return "Int8Array"; }
    }

**Comment by erossignon** [comment]
IE not supported anymore
